/** Supported subscription source types. */
export type SubscriptionType = 'github_release' | 'github_tag' | 'github_issue'

/** Issue state events to monitor. */
export type IssueEvent = 'closed' | 'reopened' | 'labeled' | 'unlabeled'

/** Repo-level watch combining release and tag events. */
export interface RepoWatch {
  id: string
  owner: string
  repo: string
  label: string
  events: {
    releases: boolean
    tags: boolean
  }
  lastCheckedAt: string | null
  lastSeenReleaseId: string | null
  lastSeenTagSha: string | null
  enabled: boolean
  createdAt: string
}

/** An issue subscription item tracked by the extension. */
export interface Subscription {
  id: string
  type: SubscriptionType
  owner: string
  repo: string
  /** For github_issue subscriptions only. */
  issueNumber?: number
  /** Human-readable label for display. */
  label: string
  /** ISO timestamp of last successful check. */
  lastCheckedAt: string | null
  /** Last seen identifier (release id, tag sha, or issue state hash). */
  lastSeenId: string | null
  /** Whether the subscription is active. */
  enabled: boolean
  /** ISO timestamp of creation. */
  createdAt: string
  /** Issue events to monitor (for github_issue type). */
  issueEvents?: IssueEvent[]
}

/** A notification record generated by the extension. */
export interface NotificationRecord {
  id: string
  subscriptionId: string
  type: SubscriptionType
  title: string
  body: string
  url: string
  read: boolean
  createdAt: string
}

/** User settings stored in chrome.storage. */
export interface Settings {
  githubToken: string
  /** Poll interval in minutes. */
  pollIntervalMinutes: number
  /** Whether desktop notifications are enabled. */
  desktopNotifications: boolean
  /** Whether the first-run onboarding has been completed. */
  onboardingCompleted: boolean
  /** ISO timestamp of the last successful sync cycle. */
  lastSyncAt: string | null
  /** Remaining GitHub API requests in the current window. */
  apiRemaining: number | null
  /** UI language override, or 'auto' to follow browser language. */
  language: 'auto' | 'en' | 'zh-CN'
}

/** Default settings when none are stored. */
export const DEFAULT_SETTINGS: Settings = {
  githubToken: '',
  pollIntervalMinutes: 15,
  desktopNotifications: true,
  onboardingCompleted: false,
  lastSyncAt: null,
  apiRemaining: null,
  language: 'auto',
}

/** GitHub API: Release response (partial). */
export interface GithubRelease {
  id: number
  tag_name: string
  name: string | null
  body: string | null
  html_url: string
  published_at: string
  prerelease: boolean
}

/** GitHub API: Tag response (partial, from refs). */
export interface GithubTag {
  ref: string
  node_id: string
  url: string
  object: {
    sha: string
    type: string
    url: string
  }
}

/** GitHub API: Issue response (partial). */
export interface GithubIssue {
  id: number
  number: number
  title: string
  state: 'open' | 'closed'
  state_reason: 'completed' | 'reopened' | 'not_planned' | 'reopened' | null
  html_url: string
  updated_at: string
  labels: { name: string }[]
}

/** Result of checking a repo watch. */
export interface RepoWatchCheckResult {
  lastSeenReleaseId: string | null
  lastSeenTagSha: string | null
  notifications: Omit<NotificationRecord, 'id' | 'subscriptionId' | 'read' | 'createdAt'>[]
}

/** Result of a subscription check. */
export interface CheckResult {
  hasUpdate: boolean
  newId: string
  notifications: Omit<NotificationRecord, 'id' | 'subscriptionId' | 'read' | 'createdAt'>[]
}
